
package com.vmware.vim25;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VimService", targetNamespace = "urn:vim25Service", wsdlLocation = "vimService.wsdl")
public class VimService
    extends Service
{

    private final static URL VIMSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(VimService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = VimService.class.getResource(VimService.class.getSimpleName() + ".class");
            url = new URL(baseUrl, "vimService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'vimService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VIMSERVICE_WSDL_LOCATION = url;
    }

    public VimService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VimService() {
        super(VIMSERVICE_WSDL_LOCATION, new QName("urn:vim25Service", "VimService"));
    }

    /**
     * 
     * @return
     *     returns VimPortType
     */
    @WebEndpoint(name = "VimPort")
    public VimPortType getVimPort() {
        return super.getPort(new QName("urn:vim25Service", "VimPort"), VimPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VimPortType
     */
    @WebEndpoint(name = "VimPort")
    public VimPortType getVimPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:vim25Service", "VimPort"), VimPortType.class, features);
    }

}
